steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [
    "-c", 
    "mkdir -p /workspace/secrets && echo $$GEE_KEY > /workspace/secrets/ecoshard-202922-99e843371bf0.json"]
  secretEnv: ["GEE_KEY"]

# running docker-compose
- name: 'docker/compose:1.29.2'
  args: ['up', '-d']

availableSecrets:
  secretManager:
    - versionName: projects/587088520267/secrets/gee_key/versions/1
      env: GEE_KEY
