steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'echo $$GH_TOKEN > /workspace/secrets/ecoshard-202922-99e843371bf0.json' ]
  secretEnv: ['GH_TOKEN']
# running docker-compose
- name: 'docker/compose:1.29.2'
  args: ['up', '-d']

availableSecrets:
  secretManager:
    - versionName: projects/587088520267/secrets/gee_key/versions/1
      env: GH_TOKEN
