version: '3.6'

services:
  frontend:
    container_name: frontend
    build: docker_contexts/frontend
    tty: true
  backend:
    container_name: backend
    hostname: backend_api
    build: docker_contexts/backend
    tty: true
    entrypoint: [
      "waitress-serve", "--expose-tracebacks", "--listen=0.0.0.0:5000", "--call", "api:create_app"]
    secrets:
      - gee_key
    environment:
      - GEE_KEY_PATH=/run/secrets/gee_key
  nginx:
    image: nginx:latest
    volumes:
      - ./docker_contexts/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

secrets:
  gee_key:
    file: ./secrets/ecoshard-202922-99e843371bf0.json
