version: '3.6'

services:
  frontend:
    container_name: frontend
    build: docker_contexts/frontend
    tty: true
  backend:
    container_name: backend
    hostname: backend_api
    build: docker_contexts/backend
    volumes:
      - ./docker_contexts/backend:/usr/local/pcld_api
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '2'
    tty: true
    entrypoint: [
      "waitress-serve", "--host=0.0.0.0", "--port=5000", "app:app"
    ]
    ports:
      - 80:5000
  nginx:
    image: nginx:latest
    volumes:
      - ./docker_contexts/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
