"""adding abudance

Revision ID: 14c18d8b9848
Revises: 4f38750bdcd5
Create Date: 2024-02-12 10:07:11.313310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c18d8b9848'
down_revision: Union[str, None] = '4f38750bdcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abundance',
    sa.Column('id_key', sa.Integer(), nullable=False),
    sa.Column('abundance_class', sa.String(), nullable=True),
    sa.Column('order', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('genus', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.Column('sub_species', sa.String(), nullable=True),
    sa.Column('morphospecies', sa.String(), nullable=True),
    sa.Column('life_stage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abundance')
    # ### end Alembic commands ###
