"""adding sample

Revision ID: 7ccdc3f6102b
Revises: 36847c8ee35a
Create Date: 2024-02-12 09:30:04.743381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccdc3f6102b'
down_revision: Union[str, None] = '36847c8ee35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('id_key', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('local_time', sa.String(), nullable=True),
    sa.Column('replicate', sa.String(), nullable=True),
    sa.Column('sampling_effort', sa.String(), nullable=False),
    sa.Column('observation', sa.String(), nullable=False),
    sa.Column('observer_id', sa.String(), nullable=False),
    sa.Column('response_variable', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('sampling_method', sa.String(), nullable=False),
    sa.Column('sampler_type', sa.String(), nullable=False),
    sa.Column('functional_type', sa.String(), nullable=False),
    sa.Column('crop_commercial_name', sa.String(), nullable=False),
    sa.Column('crop_latin_name', sa.String(), nullable=False),
    sa.Column('growth_stage_of_crop_at_sampling', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    # ### end Alembic commands ###
