"""lowercase

Revision ID: bccd0abb1b14
Revises: e79e8044c9f0
Create Date: 2024-02-12 10:12:10.616980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccd0abb1b14'
down_revision: Union[str, None] = 'e79e8044c9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'Enemy_class')
    op.drop_column('activity', 'Pest_family')
    op.drop_column('activity', 'Pest_life_stage')
    op.drop_column('activity', 'Pest_class')
    op.drop_column('activity', 'Enemy_order')
    op.drop_column('activity', 'Pest_order')
    op.drop_column('activity', 'Enemy_sub_species')
    op.drop_column('activity', 'Pest_species')
    op.drop_column('activity', 'Pest_sub_species')
    op.drop_column('activity', 'Enemy_species')
    op.drop_column('activity', 'Enemy_family')
    op.drop_column('activity', 'Pest_morphospecies')
    op.drop_column('activity', 'Enemy_morphospecies')
    op.drop_column('activity', 'Enemy_lifestage')
    op.add_column('activity', sa.Column('pest_class', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_order', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_family', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_species', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_sub_species', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_morphospecies', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('pest_life_stage', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_class', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_order', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_family', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_species', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_sub_species', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_morphospecies', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('enemy_lifestage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('Enemy_lifestage', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_morphospecies', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_morphospecies', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_family', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_species', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_sub_species', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_species', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_sub_species', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_order', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_order', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_class', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_life_stage', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Pest_family', sa.VARCHAR(), nullable=True))
    op.add_column('activity', sa.Column('Enemy_class', sa.VARCHAR(), nullable=True))
    op.drop_column('activity', 'enemy_lifestage')
    op.drop_column('activity', 'enemy_morphospecies')
    op.drop_column('activity', 'enemy_sub_species')
    op.drop_column('activity', 'enemy_species')
    op.drop_column('activity', 'enemy_family')
    op.drop_column('activity', 'enemy_order')
    op.drop_column('activity', 'enemy_class')
    op.drop_column('activity', 'pest_life_stage')
    op.drop_column('activity', 'pest_morphospecies')
    op.drop_column('activity', 'pest_sub_species')
    op.drop_column('activity', 'pest_species')
    op.drop_column('activity', 'pest_family')
    op.drop_column('activity', 'pest_order')
    op.drop_column('activity', 'pest_class')
    # ### end Alembic commands ###
