"""adding activity

Revision ID: e79e8044c9f0
Revises: 14c18d8b9848
Create Date: 2024-02-12 10:07:42.446089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e79e8044c9f0'
down_revision: Union[str, None] = '14c18d8b9848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id_key', sa.Integer(), nullable=False),
    sa.Column('Pest_class', sa.String(), nullable=True),
    sa.Column('Pest_order', sa.String(), nullable=True),
    sa.Column('Pest_family', sa.String(), nullable=True),
    sa.Column('Pest_species', sa.String(), nullable=True),
    sa.Column('Pest_sub_species', sa.String(), nullable=True),
    sa.Column('Pest_morphospecies', sa.String(), nullable=True),
    sa.Column('Pest_life_stage', sa.String(), nullable=True),
    sa.Column('Enemy_class', sa.String(), nullable=True),
    sa.Column('Enemy_order', sa.String(), nullable=True),
    sa.Column('Enemy_family', sa.String(), nullable=True),
    sa.Column('Enemy_species', sa.String(), nullable=True),
    sa.Column('Enemy_sub_species', sa.String(), nullable=True),
    sa.Column('Enemy_morphospecies', sa.String(), nullable=True),
    sa.Column('Enemy_lifestage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
